### ISSUE TITLE
Excuse me, which program can read the .h5 dataset file?

### ISSUE THREAD

**Issue by Happytreety** [robertocalandra/the-feeling-of-success#1]
Excuse me, which program can read the .h5 dataset file?

**Comment by robertocalandra** [comment]
.h5 is the extension for the HDF5 format. Python has a few libraries to read .h5 files (e.g., https://pypi.org/project/h5py/). 
Here is one more pointer: https://www.h5py.org/
Let me know if you still have issues loading the data.

**Comment by Bugs-Bunny01** [comment]
> .h5 is the extension for the HDF5 format. Python has a few libraries to read .h5 files (e.g., https://pypi.org/project/h5py/). Here is one more pointer: https://www.h5py.org/ Let me know if you still have issues loading the data.

hi, can you open source data sets in common format? I am not used to using data sets in.h5 format

**Comment by robertocalandra** [comment]
Hi @Bugs-Bunny01,
hdf5 is a common and widely used format for long-term dataset storage.
Given the size of the dataset I do not plan to host other file formats for the time being.
What is the exact issue that you are encountering with loading hdf5 files?

**Comment by Bugs-Bunny01** [comment]
hi, thanks for the reply.
I need to preprocess the data set to perform irregular cropping on the image. If it is a.h5 format file, I have no way to control whether the cropping program is correct or not

**Comment by Bugs-Bunny01** [comment]
> Hi @Bugs-Bunny01, hdf5 is a common and widely used format for long-term dataset storage. Given the size of the dataset I do not plan to host other file formats for the time being. What is the exact issue that you are encountering with loading hdf5 files?

hi, thanks for the reply.
I need to preprocess the data set to perform irregular cropping on the image. If it is a.h5 format file, I have no way to control whether the cropping program is correct or not

**Comment by robertocalandra** [comment]
@Bugs-Bunny01
The hdf5 contain a collection of raw data. This means that before cropping the images, you need to open the hdf5 and load the individual images out of the file. After you do that, cropping should be straightforward, and you will be able to visualize the images.

**Comment by Bugs-Bunny01** [comment]
> @Bugs-Bunny01 The hdf5 contain a collection of raw data. This means that before cropping the images, you need to open the hdf5 and load the individual images out of the file. After you do that, cropping should be straightforward, and you will be able to visualize the images.
hi, thanks for the reply.
However, I tried the h5py conversion method to convert tensors to images, but the original images were not available

**Comment by robertocalandra** [comment]
Please run the Python notebook for how to extract images (https://drive.google.com/file/d/1i9zwqLF6w8h2EJKJCLtKAyeanwPgoxHn/view?usp=drive_web). 
If something is not working as intended in the Python notebook, please feel free to open a new issue
